//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Student
    {
        public int StudentID { get; set; }
        public int BookID { get; set; }
        public Nullable<System.DateTime> LoadnedStartDate { get; set; }
        public Nullable<System.DateTime> LoanedEndDate { get; set; }
        public int ID { get; set; }
        public int Price { get; set; }
        public bool Control { get; set; }
        public int DEPT { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
